### ISSUE TITLE
The path display format is incorrect, and the model cannot be loaded

### ISSUE THREAD

**Issue by bingtangxin** [s0md3v/sd-webui-roop#83]
![image](https://github.com/s0md3v/sd-webui-roop/assets/67434753/8097ab83-2ea0-445b-b73f-0494615b9fb3)
![image](https://github.com/s0md3v/sd-webui-roop/assets/67434753/1ca32c37-6dae-41e0-a6f8-079581abcb8f)

**Comment by Keno0088** [comment]
So it seems like I'm not the only one.

![image](https://github.com/s0md3v/sd-webui-roop/assets/137590963/a073424e-8d09-49d9-8f4b-3a7b4d89d6df)

Hope it's not a user error, and much thanks in advance.

**Comment by s0md3v** [comment]
It should be fixed now.

**Comment by Keno0088** [comment]
I've updated it via the UI update, also checked that the faceswap.py's mod timestamp is today (after your update). 

I've closed the UI completely and shut it down and re-started Automatic1111, and the error is the same. Should be downloading another patch or a file?

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}| 16/16 [01:07<00:00,  4.49s/it]
find model: C:\Users\joker/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Error running postprocess_batch: G:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\scripts.py", line 463, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "G:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "G:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 123, in swap_face
    source_face = get_face_single(source_img, face_index=0)
  File "G:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 76, in get_face_single
    face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\joker/.insightface\models\buffalo_l\w600k_r50.onnx failed:Protobuf parsing failed.

**Comment by bingtangxin** [comment]
My problem has been solved since the author's last update. I simply uninstalled the plugin and then reinstalled it. You can try it. @Keno0088

**Comment by Keno0088** [comment]
Thanks for that @bingtangxin. Unfortunately, I've done a reinstallation of the plugin but it's still not working.

I've done several testing and I managed to get a different error message

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}| 20/20 [01:23<00:00,  4.39s/it]
find model: C:\Users\joker/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
G:\stable-diffusion-webui\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\joker/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Error running postprocess_batch: G:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\scripts.py", line 463, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "G:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "G:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 132, in swap_face
    result = face_swapper.get(result, target_face, source_face)
AttributeError: 'NoneType' object has no attribute 'get'

@s0md3v I didn't want to open a million tickets, so I'm putting it here, in the hopes that you can see it.

Since your last update, I've already updated the plugin, and based on what Bing is saying, your fix worked for him, but unfortunately, I still have something that's blocking mine.....

**Comment by bingtangxin** [comment]
The author mentions in the README document:

If you encounter 'NoneType' object has no attribute 'get' error, download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside your <webui_dir>/models/roop/ directory.

https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx

I hope it helps. @Keno0088

**Comment by Limbicnation** [comment]
> The author mentions in the README document:
> 
> If you encounter 'NoneType' object has no attribute 'get' error, download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside your <webui_dir>/models/roop/ directory.
> 
> https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx
> 
> I hope it helps. @Keno0088

Unfortunately, this method didn't work for me.

**Comment by VitaliyAT** [comment]
> Just leaving a thank you to both of you guys. It didn't work when I replaced. I switched it off and turned the PC back on and it's working. I'm not sure what "exactly" needed to be fixed, but it's working, so let's call it a win. :)

For me it's not working. Full log looking so:
```
venv "C:\[Ai]\1111\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing requirements
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
2023-07-20 22:17:29,264 - roop - INFO - roop v0.0.2
2023-07-20 22:17:29,264 - roop - INFO - roop v0.0.2
Loading weights [6ce0161689] from C:\[Ai]\1111\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
2023-07-20 22:17:29,942 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
2023-07-20 22:17:30,099 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
preload_extensions_git_metadata for 8 extensions took 0.10s
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.9s (import torch: 1.8s, import gradio: 1.1s, import ldm: 0.5s, other imports: 1.8s, load scripts: 1.1s, create ui: 0.3s, gradio launch: 0.1s).
Creating model from config: C:\[Ai]\1111\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 4.4s (load weights from disk: 0.5s, create model: 0.3s, apply weights to model: 1.9s, apply half(): 0.4s, move model to device: 1.2s, calculate empty prompt: 0.1s).
```
